### PR TITLE
ZBUG-1469: Fixed Zimbra Docs status page reporting by asking the docs status

### PR DESCRIPTION
**Pull request by ZeXtrasJay**
Printing the status of every docs server

### CODE REVIEW

**Comment by Prashantsurana** [comment]
what is the target release? is there any dependency ?

**Comment by Prashantsurana** [comment]
> what is the target release? is there any dependency ?

@ZeXtrasJay

**Comment by ZeXtrasJay** [comment]
There is no specific target release, next available slot for 8.8.15.
This patch is dependent upon `zxsuite` command but if not present it'll skip the check

**Comment by Prashantsurana** [comment]
@umagmrit  and @pallavikhairnar21  can you please add this to 8.8.15 and 9.0.0 p3. 
Please create a ticket.

**Pull request merged**
